# CMake generated Testfile for 
# Source directory: C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel
# Build directory: C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_smoke]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/Debug/test_smoke.exe")
  set_tests_properties([=[test_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;118;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_smoke]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/Release/test_smoke.exe")
  set_tests_properties([=[test_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;118;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_smoke]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/MinSizeRel/test_smoke.exe")
  set_tests_properties([=[test_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;118;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_smoke]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/RelWithDebInfo/test_smoke.exe")
  set_tests_properties([=[test_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;118;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
else()
  add_test([=[test_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_geometry]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/Debug/test_geometry.exe")
  set_tests_properties([=[test_geometry]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;119;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_geometry]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/Release/test_geometry.exe")
  set_tests_properties([=[test_geometry]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;119;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_geometry]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/MinSizeRel/test_geometry.exe")
  set_tests_properties([=[test_geometry]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;119;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_geometry]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/RelWithDebInfo/test_geometry.exe")
  set_tests_properties([=[test_geometry]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;119;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
else()
  add_test([=[test_geometry]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_topo_naming]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/Debug/test_topo_naming.exe")
  set_tests_properties([=[test_topo_naming]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;122;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_topo_naming]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/Release/test_topo_naming.exe")
  set_tests_properties([=[test_topo_naming]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;122;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_topo_naming]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/MinSizeRel/test_topo_naming.exe")
  set_tests_properties([=[test_topo_naming]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;122;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_topo_naming]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/RelWithDebInfo/test_topo_naming.exe")
  set_tests_properties([=[test_topo_naming]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;122;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
else()
  add_test([=[test_topo_naming]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_sketch_solver]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/Debug/test_sketch_solver.exe")
  set_tests_properties([=[test_sketch_solver]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;125;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_sketch_solver]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/Release/test_sketch_solver.exe")
  set_tests_properties([=[test_sketch_solver]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;125;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_sketch_solver]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/MinSizeRel/test_sketch_solver.exe")
  set_tests_properties([=[test_sketch_solver]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;125;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_sketch_solver]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/RelWithDebInfo/test_sketch_solver.exe")
  set_tests_properties([=[test_sketch_solver]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;125;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
else()
  add_test([=[test_sketch_solver]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_boolean_stress]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/Debug/test_boolean_stress.exe")
  set_tests_properties([=[test_boolean_stress]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;128;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_boolean_stress]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/Release/test_boolean_stress.exe")
  set_tests_properties([=[test_boolean_stress]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;128;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_boolean_stress]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/MinSizeRel/test_boolean_stress.exe")
  set_tests_properties([=[test_boolean_stress]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;128;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_boolean_stress]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/RelWithDebInfo/test_boolean_stress.exe")
  set_tests_properties([=[test_boolean_stress]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;128;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
else()
  add_test([=[test_boolean_stress]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_step_roundtrip]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/Debug/test_step_roundtrip.exe")
  set_tests_properties([=[test_step_roundtrip]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;131;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_step_roundtrip]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/Release/test_step_roundtrip.exe")
  set_tests_properties([=[test_step_roundtrip]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;131;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_step_roundtrip]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/MinSizeRel/test_step_roundtrip.exe")
  set_tests_properties([=[test_step_roundtrip]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;131;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_step_roundtrip]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/RelWithDebInfo/test_step_roundtrip.exe")
  set_tests_properties([=[test_step_roundtrip]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;131;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
else()
  add_test([=[test_step_roundtrip]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_serialize]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/Debug/test_serialize.exe")
  set_tests_properties([=[test_serialize]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;134;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_serialize]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/Release/test_serialize.exe")
  set_tests_properties([=[test_serialize]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;134;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_serialize]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/MinSizeRel/test_serialize.exe")
  set_tests_properties([=[test_serialize]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;134;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_serialize]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/RelWithDebInfo/test_serialize.exe")
  set_tests_properties([=[test_serialize]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;134;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
else()
  add_test([=[test_serialize]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_robustness]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/Debug/test_robustness.exe")
  set_tests_properties([=[test_robustness]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;137;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_robustness]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/Release/test_robustness.exe")
  set_tests_properties([=[test_robustness]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;137;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_robustness]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/MinSizeRel/test_robustness.exe")
  set_tests_properties([=[test_robustness]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;137;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_robustness]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/RelWithDebInfo/test_robustness.exe")
  set_tests_properties([=[test_robustness]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;137;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
else()
  add_test([=[test_robustness]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_feature_tree]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/Debug/test_feature_tree.exe")
  set_tests_properties([=[test_feature_tree]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;140;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_feature_tree]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/Release/test_feature_tree.exe")
  set_tests_properties([=[test_feature_tree]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;140;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_feature_tree]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/MinSizeRel/test_feature_tree.exe")
  set_tests_properties([=[test_feature_tree]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;140;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_feature_tree]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/RelWithDebInfo/test_feature_tree.exe")
  set_tests_properties([=[test_feature_tree]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;140;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
else()
  add_test([=[test_feature_tree]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_foundation]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/Debug/test_foundation.exe")
  set_tests_properties([=[test_foundation]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;143;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_foundation]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/Release/test_foundation.exe")
  set_tests_properties([=[test_foundation]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;143;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_foundation]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/MinSizeRel/test_foundation.exe")
  set_tests_properties([=[test_foundation]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;143;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_foundation]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/RelWithDebInfo/test_foundation.exe")
  set_tests_properties([=[test_foundation]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;143;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
else()
  add_test([=[test_foundation]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_foundation_hardened]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/Debug/test_foundation_hardened.exe")
  set_tests_properties([=[test_foundation_hardened]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;146;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_foundation_hardened]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/Release/test_foundation_hardened.exe")
  set_tests_properties([=[test_foundation_hardened]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;146;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_foundation_hardened]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/MinSizeRel/test_foundation_hardened.exe")
  set_tests_properties([=[test_foundation_hardened]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;146;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_foundation_hardened]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/RelWithDebInfo/test_foundation_hardened.exe")
  set_tests_properties([=[test_foundation_hardened]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;146;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
else()
  add_test([=[test_foundation_hardened]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_mesh]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/Debug/test_mesh.exe")
  set_tests_properties([=[test_mesh]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;149;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_mesh]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/Release/test_mesh.exe")
  set_tests_properties([=[test_mesh]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;149;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_mesh]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/MinSizeRel/test_mesh.exe")
  set_tests_properties([=[test_mesh]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;149;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_mesh]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/RelWithDebInfo/test_mesh.exe")
  set_tests_properties([=[test_mesh]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;149;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
else()
  add_test([=[test_mesh]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_foundation_production]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/Debug/test_foundation_production.exe")
  set_tests_properties([=[test_foundation_production]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;151;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_foundation_production]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/Release/test_foundation_production.exe")
  set_tests_properties([=[test_foundation_production]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;151;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_foundation_production]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/MinSizeRel/test_foundation_production.exe")
  set_tests_properties([=[test_foundation_production]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;151;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_foundation_production]=] "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/build_msvc/RelWithDebInfo/test_foundation_production.exe")
  set_tests_properties([=[test_foundation_production]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;112;add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;151;oreo_add_test;C:/Users/AbhinavPutta/Desktop/projects/oreoCAD/oreo-kernel/CMakeLists.txt;0;")
else()
  add_test([=[test_foundation_production]=] NOT_AVAILABLE)
endif()
