// SPDX-License-Identifier: LGPL-2.1-or-later

// mapped_name.h — Encoded element name with operation history.
// Inspired by FreeCAD 1.0's MappedName (LGPL-2.1+), clean reimplementation.
//
// A MappedName encodes the history of an element through operations:
//   ";:H1aFace1;:M" = Face1 from operation 0x1a, modified
//   ";:H1aFace1;:M;:H2b;:G" = ... then generated by operation 0x2b
//
// Postfix codes (from FreeCAD's element naming convention):
//   ;:H<hex>  — operation tag in hex (v1 identity scalar — DEPRECATED writer, reader kept)
//   ;:T<dec>  — operation tag in decimal (v1 legacy)
//   ;:M       — element was modified by this operation
//   ;:G       — element was generated (new) by this operation
//   ;:MG      — element was both modified and generated
//   ;:C       — child element
//   ;:U       — upper element
//   ;:L       — lower element
//   ;:D       — duplicate disambiguation
//   ;:P<16hex>.<16hex> — full ShapeIdentity postfix (oreo v2 extension):
//               carries {documentId, counter} as two fixed-width 64-bit
//               hex fields joined by a dot. This is the v2 authoritative
//               identity carrier. Readers handle a mix of ;:P and ;:H via
//               the rightmost-marker rule in extractShapeIdentity
//               (docs/identity-model.md §4.3 rule 4).
//   ;:Q       — document-identity postfix (oreo v1 extension): carries full
//               64-bit documentId hex so cross-document identity is preserved
//               in the name. Kept in v2 for names that only have ;:H (no
//               ;:P per-op identity). Parsers that don't know about ;:Q can
//               ignore it safely — it never interacts with ;:H tag extraction.

#ifndef OREO_MAPPED_NAME_H
#define OREO_MAPPED_NAME_H

#include "core/shape_identity.h"

#include <cinttypes>
#include <cstdint>
#include <cstdio>
#include <functional>
#include <ostream>
#include <string>
#include <string_view>

namespace oreo {

// Prefix/postfix constants — compatible with FreeCAD's encoding.
namespace ElementCodes {
    constexpr const char* MAP_PREFIX = ";";
    constexpr const char* MISSING_PREFIX = "?";
    constexpr const char* POSTFIX_TAG = ";:H";         // hex tag
    constexpr const char* POSTFIX_DECIMAL_TAG = ";:T";  // decimal tag
    constexpr const char* POSTFIX_MOD = ";:M";          // modified
    constexpr const char* POSTFIX_GEN = ";:G";          // generated
    constexpr const char* POSTFIX_MODGEN = ";:MG";      // modified+generated
    constexpr const char* POSTFIX_CHILD = ";:C";        // child element
    constexpr const char* POSTFIX_UPPER = ";:U";
    constexpr const char* POSTFIX_LOWER = ";:L";
    constexpr const char* POSTFIX_DUPLICATE = ";D";
    constexpr const char* POSTFIX_INDEX = ";:I";
    constexpr const char* POSTFIX_EXTERNAL = ";:X";
    // POSTFIX_IDENTITY is the v2 authoritative per-op identity carrier.
    // Encoded as exactly 32 hex characters: 16 hex documentId
    // concatenated with 16 hex counter, no separator. The dot
    // separator that would have been more readable is rejected by the
    // FreeCAD-extracted Data::MappedName validation (which forbids '.'
    // and whitespace in mapped names — see freecad/ElementMap.cpp:545),
    // so we use pure hex. Fixed width is still required for
    // deterministic byte-exact goldens.
    // Chosen as ";:P" because ";:I" was already POSTFIX_INDEX — see
    // identity-model.md §4.2 for the open-question history.
    constexpr const char* POSTFIX_IDENTITY = ";:P";
    constexpr size_t POSTFIX_IDENTITY_HEX_LEN = 32;  // "<16hex><16hex>"
    // POSTFIX_DOC encodes the full 64-bit documentId as exactly 16 hex chars.
    // It is written once per top-level name so that cross-document identity
    // survives the (low32(docId) << 32 | counter) tag encoding — which throws
    // away the high 32 bits of documentId. See docs in this header.
    constexpr const char* POSTFIX_DOC = ";:Q";
    constexpr size_t POSTFIX_DOC_HEX_LEN = 16;  // 64-bit docId in hex
} // namespace ElementCodes

class MappedName {
public:
    MappedName() = default;

    explicit MappedName(const std::string& encoded)
        : data_(encoded) {}

    explicit MappedName(std::string&& encoded)
        : data_(std::move(encoded)) {}

    MappedName(const char* data)
        : data_(data ? data : "") {}

    bool empty() const { return data_.empty(); }

    const std::string& data() const { return data_; }
    const char* c_str() const { return data_.c_str(); }
    size_t size() const { return data_.size(); }

    // Append a postfix (e.g., ";:M" for modified)
    MappedName& appendPostfix(const char* postfix) {
        data_ += postfix;
        return *this;
    }

    // Append hex-encoded operation tag. The tag is formatted as a full 64-bit
    // hexadecimal value using PRIx64 — this is critical on Windows where
    // `long` is 32-bit and a `%lx` format would silently truncate the high
    // 32 bits of a 64-bit tag. Treat the tag as unsigned for formatting so
    // negative tags encode as their two's-complement hex (matches FreeCAD).
    //
    // DEPRECATED in v2: use appendShapeIdentity() instead. ;:H is now a
    // read-only compatibility marker — new names should carry ;:P.
    [[deprecated("use appendShapeIdentity() — the v1 ;:H carrier squeezes "
                 "documentId into the same scalar as counter and loses "
                 "high bits")]]
    MappedName& appendTag(std::int64_t tag) {
        char buf[32];
        std::snprintf(buf, sizeof(buf), "%" PRIx64,
                      static_cast<std::uint64_t>(tag));
        data_ += ElementCodes::POSTFIX_TAG;
        data_ += buf;
        return *this;
    }

    // Append a full 64+64 ShapeIdentity postfix: ";:P<32hex>".
    // Two concatenated 16-char hex fields (documentId, then counter).
    // No separator between the fields — FreeCAD's mapped-name validator
    // rejects '.' and whitespace, so we stay alphanumeric.
    // Invariant: the identity must be valid (counter != 0). Passing a
    // counter==0 identity writes an all-zero counter field, which
    // decoders flag as invalid — use isValid() on the caller side to
    // gate.
    MappedName& appendShapeIdentity(ShapeIdentity id) {
        char buf[36];  // 32 chars + NUL + slack
        std::snprintf(buf, sizeof(buf), "%016llx%016llx",
                      static_cast<unsigned long long>(id.documentId),
                      static_cast<unsigned long long>(id.counter));
        data_ += ElementCodes::POSTFIX_IDENTITY;
        data_ += buf;
        return *this;
    }

    // Append the full 64-bit documentId as a ";:Q<16-hex>" postfix. This is
    // a no-op for documentId == 0 (single-document mode) to keep names short
    // and backward-compatible. The postfix is exactly 16 hex chars so the
    // full 64-bit documentId survives round-trips through the naming and
    // serialization layers — the high 32 bits of documentId are otherwise
    // lost in the (low32(docId) << 32 | counter) tag encoding used by
    // TagAllocator. Callers that build element names with cross-document
    // semantics should emit this once per top-level name.
    MappedName& appendDocumentId(std::uint64_t documentId) {
        if (documentId == 0) return *this;
        char buf[20];
        std::snprintf(buf, sizeof(buf), "%016" PRIx64, documentId);
        data_ += ElementCodes::POSTFIX_DOC;
        data_ += buf;
        return *this;
    }

    // Check if name starts with the element-map prefix ";"
    bool isMapped() const {
        return !data_.empty() && data_[0] == ';';
    }

    // Find last occurrence of a postfix
    size_t rfind(const char* postfix) const {
        return data_.rfind(postfix);
    }

    // Find first occurrence
    size_t find(const char* postfix, size_t pos = 0) const {
        return data_.find(postfix, pos);
    }

    bool operator==(const MappedName& o) const { return data_ == o.data_; }
    bool operator!=(const MappedName& o) const { return data_ != o.data_; }
    bool operator<(const MappedName& o) const { return data_ < o.data_; }

    friend std::ostream& operator<<(std::ostream& os, const MappedName& n) {
        return os << n.data_;
    }

private:
    std::string data_;
};

} // namespace oreo

// Hash support
template<>
struct std::hash<oreo::MappedName> {
    std::size_t operator()(const oreo::MappedName& n) const noexcept {
        return std::hash<std::string>{}(n.data());
    }
};

#endif // OREO_MAPPED_NAME_H
