// mapped_name.h — Encoded element name with operation history.
// Inspired by FreeCAD 1.0's MappedName (LGPL-2.1+), clean reimplementation.
//
// A MappedName encodes the history of an element through operations:
//   ";:H1aFace1;:M" = Face1 from operation 0x1a, modified
//   ";:H1aFace1;:M;:H2b;:G" = ... then generated by operation 0x2b
//
// Postfix codes (from FreeCAD's element naming convention):
//   ;:H<hex>  — operation tag in hex
//   ;:T<dec>  — operation tag in decimal
//   ;:M       — element was modified by this operation
//   ;:G       — element was generated (new) by this operation
//   ;:MG      — element was both modified and generated
//   ;:C       — child element
//   ;:U       — upper element
//   ;:L       — lower element
//   ;:D       — duplicate disambiguation

#ifndef OREO_MAPPED_NAME_H
#define OREO_MAPPED_NAME_H

#include <functional>
#include <ostream>
#include <string>
#include <string_view>

namespace oreo {

// Prefix/postfix constants — compatible with FreeCAD's encoding.
namespace ElementCodes {
    constexpr const char* MAP_PREFIX = ";";
    constexpr const char* MISSING_PREFIX = "?";
    constexpr const char* POSTFIX_TAG = ";:H";         // hex tag
    constexpr const char* POSTFIX_DECIMAL_TAG = ";:T";  // decimal tag
    constexpr const char* POSTFIX_MOD = ";:M";          // modified
    constexpr const char* POSTFIX_GEN = ";:G";          // generated
    constexpr const char* POSTFIX_MODGEN = ";:MG";      // modified+generated
    constexpr const char* POSTFIX_CHILD = ";:C";        // child element
    constexpr const char* POSTFIX_UPPER = ";:U";
    constexpr const char* POSTFIX_LOWER = ";:L";
    constexpr const char* POSTFIX_DUPLICATE = ";D";
    constexpr const char* POSTFIX_INDEX = ";:I";
    constexpr const char* POSTFIX_EXTERNAL = ";:X";
} // namespace ElementCodes

class MappedName {
public:
    MappedName() = default;

    explicit MappedName(const std::string& encoded)
        : data_(encoded) {}

    explicit MappedName(std::string&& encoded)
        : data_(std::move(encoded)) {}

    MappedName(const char* data)
        : data_(data ? data : "") {}

    bool empty() const { return data_.empty(); }

    const std::string& data() const { return data_; }
    const char* c_str() const { return data_.c_str(); }
    size_t size() const { return data_.size(); }

    // Append a postfix (e.g., ";:M" for modified)
    MappedName& appendPostfix(const char* postfix) {
        data_ += postfix;
        return *this;
    }

    // Append hex-encoded operation tag
    MappedName& appendTag(long tag) {
        char buf[32];
        snprintf(buf, sizeof(buf), "%lx", tag);
        data_ += ElementCodes::POSTFIX_TAG;
        data_ += buf;
        return *this;
    }

    // Check if name starts with the element-map prefix ";"
    bool isMapped() const {
        return !data_.empty() && data_[0] == ';';
    }

    // Find last occurrence of a postfix
    size_t rfind(const char* postfix) const {
        return data_.rfind(postfix);
    }

    // Find first occurrence
    size_t find(const char* postfix, size_t pos = 0) const {
        return data_.find(postfix, pos);
    }

    bool operator==(const MappedName& o) const { return data_ == o.data_; }
    bool operator!=(const MappedName& o) const { return data_ != o.data_; }
    bool operator<(const MappedName& o) const { return data_ < o.data_; }

    friend std::ostream& operator<<(std::ostream& os, const MappedName& n) {
        return os << n.data_;
    }

private:
    std::string data_;
};

} // namespace oreo

// Hash support
template<>
struct std::hash<oreo::MappedName> {
    std::size_t operator()(const oreo::MappedName& n) const noexcept {
        return std::hash<std::string>{}(n.data());
    }
};

#endif // OREO_MAPPED_NAME_H
